apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-workflow
  namespace: default
spec:
  components:
  - name: express-server
    type: webservice
    properties:
      image: stefanprodan/podinfo
      port: 9898
    traits:
    - type: ingress
      properties:
        domain: testsvc.example.com
        http:
          /: 9898
  - name: nginx-server
    type: webservice
    properties:
      image: nginx:1.21
      port: 80
