apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-workflow
  namespace: default
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: registry.cn-hangzhou.aliyuncs.com/test-fog/test:v4 # {"$imagepolicy": "default:gitops"}
        port: 9898
      traits:
        - type: ingress
          properties:
            domain: testsvc.example.com
            http:
              /: 9898
