apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-workflow
  namespace: default
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: registry.cn-hangzhou.aliyuncs.com/test-fog/test:v1 # {"$imagepolicy": "default:gitops"}
        port: 9898
      traits:
        - type: ingress
          properties:
            domain: testsvc.example.com
            http:
              /: 9898
    - name: nginx-server
      type: webservice
      properties:
        image: nginx:1.21
        port: 80
  policies:
    - name: my-policy
      type: env-binding
      properties:
        clusterManagementEngine: single-cluster
        envs:
          - name: my-env
            placement:
              namespaceSelector:
                name: prod
  workflow:
    steps:
      - name: multi-env
        type: multi-env
        properties:
          policy: my-policy
          env: my-env
