apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-workflow-test
  namespace: default
spec:
  components:
  - name: express-server-test
    type: webservice
    properties:
      image: whalesay
      port: 8000
    traits:
    - type: ingress
      properties:
        domain: testsvc-test.example.com
        http:
          /: 8000
  - name: nginx-server-test
    type: webservice
    properties:
      image: nginx:1.21
      port: 80
  workflow:
    steps:
      - name: express-server
        type: apply-application
