apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-workflow-test
  namespace: default
spec:
  components:
  - name: express-server-test
    type: webservice
    properties:
      image: stefanprodan/podinfo
      port: 9898
    traits:
    - type: ingress
      properties:
        domain: testsvc-test.example.com
        http:
          /: 9898
  - name: nginx-server-test
    type: webservice
    properties:
      image: nginx:1.21
      port: 80

  policies:
    - name: my-policy
      type: env-binding
      properties:
        clusterManagementEngine: single-cluster
        envs:
          - name: my-env
            placement:
              namespaceSelector:
                name: test
  workflow:
    steps:
      - name: deploy-test-env
        type: multi-env
        properties:
          # 指定 policy 名称
          policy: my-policy
          # 指定 policy 中的 env 名称
          env: my-env
