name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  publish:
    runs-on:
      - ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Update image automatically')"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
           go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: go build main.go

      - name: docker-build
        run: |
          ls
          cd KubeVela-GitOps-Demo
          docker build -t ghcr.io/FogDong/test-fog:$(git rev-parse --short "$GITHUB_SHA") -f Dockerfile .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: docker-push
        run: |
          docker push ghcr.io/FogDong/test-fog:$(git rev-parse --short "$GITHUB_SHA")
